### PR TITLE
Things, that need to be fixed

### LINKED ISSUE #2: Doesn't work

### PR DESCRIPTION
**Pull request by ivantverdyi**

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -26,7 +26,7 @@ void menu() {
 }
 
 int main() {
-
+//123
```
Comment (ivantverdy) [inline main.cpp:29]: recent change
